image: registry.troojer.com/troojer/repo/docker:latest
services:
  - registry.troojer.com/troojer/repo/docker:dind

variables:
  PROJECT_NAME: "ms-event"

stages:
  - build
  - package
  - deploy

build:
  image: registry.troojer.com/troojer/repo/gradle:6.7.1-jre15
  stage: build
  script:
    - gradle build

  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 day

package:
  stage: package
  script:
    - ls -alh
    - pwd
    - ls -alh build/libs/
    - docker build -t zmmdv/$PROJECT_NAME:$CI_COMMIT_SHORT_SHA .
    - docker login -u zmmdv -p zmmdv89682329P@ssw0rD
    - docker push zmmdv/$PROJECT_NAME:$CI_COMMIT_SHORT_SHA

deploy:
  image:
    name: registry.troojer.com/troojer/repo/alpine:latest
  stage: deploy
  before_script:
    - apk update
    - apk add curl
    - wget https://get.helm.sh/helm-v3.5.2-linux-amd64.tar.gz
    - tar -zxvf helm-v3.5.2-linux-amd64.tar.gz
    - mv linux-amd64/helm /usr/local/bin/helm
    - helm repo add troojer --username $HELM_USERNAME --password $HELM_PASSWORD https://chartmuseum.troojer.com
    - helm repo update
  script:
    - helm upgrade $PROJECT_NAME -n app --set image.tag=$CI_COMMIT_SHORT_SHA troojer/$PROJECT_NAME --kubeconfig $KUBECONFIG
