spring:
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    port: 5672
    connection-timeout: 3
  datasource:
    url: jdbc:postgresql://192.168.1.100:30058/ms_event
    username: postgres
    password: P@ssw0rD
  jpa:
    properties:
      hibernate:
        format_sql: true
client:
  profile:
    url: http://localhost:8083/profile/
  localization:
    url: http://localhost:8084/localization/
  tag:
    url: http://localhost:8085/tags/
  user-plan:
    url: http://localhost:8087/user-plans/
  location:
    url: http://localhost:8089/location/
  image:
    url: http://localhost:8090/private/images/
  message:
    url: http://localhost:8092/private/messages/
logging:
  my-level: INFO