spring:
  rabbitmq:
    host: ${RABBITMQ_URL}
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_USER_PASSWORD}
    port: 5672
  datasource:
    url: jdbc:postgresql://${DATABASE_URL}/ms_event
    username: ${MS_EVENT_USER}
    password: ${MS_EVENT_USER_PASSWORD}
  liquibase:
    enabled: true
    change-log: classpath:liquibase/changelog-master.yml
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    show-sql: true
server:
  port: 8080
client:
  profile:
    url: http://ms-profile:8080/profile/
  localization:
    url: http://ms-localization:8080/localization/
  tag:
    url: http://ms-tag:8080/tags/
  participant:
    url: http://ms-participant:8080/private/participants/
  user-plan:
    url: http://ms-user-plan:8080/user-plans/
  location:
    url: http://ms-location:8080/location/
  image:
    url: http://ms-image:8080/private/images/
  message:
    url: http://ms-message:8080/private/messages/
logging:
  my-level: INFO