spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/ms_interest
    username: ms_interest
    password: 666
  liquibase:
    enabled: true
    change-log: classpath:liquibase/changelog-master.yml
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
server:
  port: 8085