spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ms_event
    username: postgres
    password: postgres
client:
  localization:
    url: http://localhost:8084/localization/
  tag:
    url: http://localhost:8085/tags/


